import NavLinks from "@/components/NavLinks";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { BiHome, BiSolidPhoneCall } from "react-icons/bi";
import { GoHomeFill } from "react-icons/go";
import { RiInformationFill, RiTeamFill } from "react-icons/ri";
import { TbTriangleFilled } from "react-icons/tb";
import "./globals.css";
import Navbar from "../../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <div className='relative'>
            {/* if a link is hoverd scale it to 150 */}
            <Navbar />
            {/* <nav className='flex items-center justify-between text-xl *:duration-300'>
                  <NavLinks title='Home' icon={<GoHomeFill />} href='/' />
                  <NavLinks
                    title='Our Team'
                    icon={<RiTeamFill />}
                    href='/team'
                  />
                  <NavLinks
                    title='About Us'
                    icon={<RiInformationFill />}
                    href='/about'
                  />
                  <NavLinks
                    title='Contact Us'
                    icon={<BiSolidPhoneCall />}
                    href='/contact'
                  />
                </nav> */}
            {children}

            <div className='fixed bottom-0 w-full bg-black bg-opacity-70 z-10 p-2 backdrop-blur-md text-white text-center'>
              🚧Site is under development
            </div>
          </div>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
